CREATE TABLE HORARIOS(
    ID_HORARIO NUMBER PRIMARY KEY,
    ID_ASESOR NUMBER NOT NULL,
    FECHA DATE NOT NULL,
    HORA_INICIO VARCHAR2(5) NOT NULL,
    HORA_FIN VARCHAR2(5) NOT NULL,
    ESTADO VARCHAR2(20) DEFAULT 'DISPONIBLE',
    ACTIVO CHAR(1) DEFAULT 'S',
    FECHA_CREACION DATE DEFAULT SYSDATE,
    FECHA_ACTUALIZACION DATE DEFAULT SYSDATE,
    CONSTRAINT FK_HORARIOS FOREIGN KEY (ID_ASESOR) REFERENCES ASESORES(ID),
    CONSTRAINT CK_ESTADO CHECK (ESTADO IN ('DISPONIBLE', 'OCUPADO', 'NO_TRABAJA')),
    CONSTRAINT CK_ACTIVO CHECK (ACTIVO IN ('S', 'N'))
);

-- Crear secuencia para el ID_HORARIO
CREATE SEQUENCE SEQ_HORARIOS START WITH 1 INCREMENT BY 1;

-- Crear índice para búsquedas frecuentes
CREATE INDEX IDX_HORARIOS_FECHA ON HORARIOS(ID_ASESOR, FECHA);