SELECT 
    U.NOMBRE,
    A.AFIRMACION_DSC,
    R.VALOR
FROM ALEJO.USUARIO_AFIRMACION_RPTA UAR INNER JOIN ALEJO.USUARIO U ON UAR.USUARIO_ID = U.ID
                                       INNER JOIN ALEJO.AFIRMACIONES A ON UAR.AFIRMACION_ID = A.ID
                                       INNER JOIN ALEJO.RIASEC R ON UAR.RIASEC_ID = R.ID