-- Tabla de Usuarios
CREATE TABLE Usuario (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    apellido VARCHAR2(100),
    correo VARCHAR2(150) UNIQUE, -- Agregué UNIQUE por buenas prácticas
    password VARCHAR2(255)
);

-- Tabla de Eventos
CREATE TABLE Eventos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_event VARCHAR2(150)
);

-- Tabla de Preguntas (para los tests)
CREATE TABLE pregunta (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question VARCHAR2(4000) -- 4000 para permitir preguntas largas
);

-- Tabla de Campos (Categorías de las carreras)
CREATE TABLE campo (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(150)
);

-- Tabla de Skills (Habilidades)
CREATE TABLE skills (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(150)
);

-- Tabla de Tareas
CREATE TABLE tareas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(150)
);

-- Tabla de Personajes
CREATE TABLE personajes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    apellido VARCHAR2(100),
    descripcion VARCHAR2(4000) -- "desc" es palabra reservada, se usa comillas dobles o cambiar nombre
);