-- Tabla Carreras (Depende de Campo)
CREATE TABLE carreras (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_carrera VARCHAR2(150),
    carrera_desc VARCHAR2(4000),
    carrera_icono VARCHAR2(255), -- Probablemente una URL o ruta
    fk_campo NUMBER,
    CONSTRAINT fk_carreras_campo FOREIGN KEY (fk_campo) REFERENCES campo(id)
);

-- Tabla Asesores (Depende de Carreras, según la línea en el diagrama)
CREATE TABLE asesores (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    apellido VARCHAR2(100),
    fk_carrera NUMBER,
    CONSTRAINT fk_asesores_carrera FOREIGN KEY (fk_carrera) REFERENCES carreras(id)
);

-- Relación Usuario - Evento
CREATE TABLE Usuario_evento (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_usuario NUMBER,
    fk_evento NUMBER,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_usev_usuario FOREIGN KEY (fk_usuario) REFERENCES Usuario(id),
    CONSTRAINT fk_usev_evento FOREIGN KEY (fk_evento) REFERENCES Eventos(id)
);

-- Respuestas de los tests
CREATE TABLE respuesta (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_usuario NUMBER,
    fk_test_pregunta NUMBER,
    valor VARCHAR2(255), -- O NUMBER si el valor es numérico
    CONSTRAINT fk_resp_usuario FOREIGN KEY (fk_usuario) REFERENCES Usuario(id),
    CONSTRAINT fk_resp_pregunta FOREIGN KEY (fk_test_pregunta) REFERENCES pregunta(id)
);

-- Asesorías agendadas
CREATE TABLE asesoria_usuario (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_asesor NUMBER,
    fk_usuario NUMBER,
    dia DATE,
    hora VARCHAR2(20), -- O TIMESTAMP si prefieres formato fecha/hora estricto
    link VARCHAR2(255),
    CONSTRAINT fk_asesu_asesor FOREIGN KEY (fk_asesor) REFERENCES asesores(id),
    CONSTRAINT fk_asesu_usuario FOREIGN KEY (fk_usuario) REFERENCES Usuario(id)
);

-- Carreras Recomendadas (Resultado del test probablemente)
CREATE TABLE carreras_recomendadas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_usuario NUMBER,
    fk_carreras NUMBER,
    valor VARCHAR2(100), -- Score o porcentaje de afinidad
    CONSTRAINT fk_crec_usuario FOREIGN KEY (fk_usuario) REFERENCES Usuario(id),
    CONSTRAINT fk_crec_carrera FOREIGN KEY (fk_carreras) REFERENCES carreras(id)
);

-- Videos asociados a carreras
CREATE TABLE videos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(255),
    link VARCHAR2(255),
    fk_carrera NUMBER,
    CONSTRAINT fk_videos_carrera FOREIGN KEY (fk_carrera) REFERENCES carreras(id)
);

-- Relación Carreras - Skills
CREATE TABLE carreras_skills (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_carrera NUMBER,
    fk_skills NUMBER,
    CONSTRAINT fk_cask_carrera FOREIGN KEY (fk_carrera) REFERENCES carreras(id),
    CONSTRAINT fk_cask_skill FOREIGN KEY (fk_skills) REFERENCES skills(id)
);

-- Relación Carreras - Tareas
CREATE TABLE carrera_tareas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_carrera NUMBER,
    fk_tarea NUMBER,
    CONSTRAINT fk_cata_carrera FOREIGN KEY (fk_carrera) REFERENCES carreras(id),
    CONSTRAINT fk_cata_tarea FOREIGN KEY (fk_tarea) REFERENCES tareas(id)
);

-- Relación Carreras - Personajes
CREATE TABLE carreras_personajes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_carrera NUMBER,
    fk_personajes NUMBER,
    CONSTRAINT fk_cape_carrera FOREIGN KEY (fk_carrera) REFERENCES carreras(id),
    CONSTRAINT fk_cape_personaje FOREIGN KEY (fk_personajes) REFERENCES personajes(id)
);